version: '2.1'
services:
  splash:
    image: scrapinghub/splash
   
    networks:
      nginx-splash:
        aliases:
          - ns_splash

  nginx:
    build: .
    links:
     - splash
    depends_on:
     - splash
    ports:
      # - 8051:8051
      - "8051:8051"  
    networks:
      nginx-splash:
        aliases:
          - ns_nginx

networks:
  nginx-splash:
    driver: bridge
    # enable_ipv6: true
    ipam:
      driver: default
      config:
      - subnet: 172.16.238.0/24
        gateway: 172.16.238.1
      # - subnet: 2001:3984:3989::/64
      #   gateway: 2001:3984:3989::1