version: '2.1'
services:
  splash1:
    image: scrapinghub/splash
    networks:
      nginx-splash:
        aliases:
          - ns_splash_1
  
  splash2:
    image: scrapinghub/splash
   
    networks:
      nginx-splash:
        aliases:
          - ns_splash_2

  splash3:
    image: scrapinghub/splash
    networks:
      nginx-splash:
        aliases:
          - ns_splash_3

  nginx:
    build: .
    links:
     - splash1
     - splash2
     - splash3
    depends_on:
     - splash1
     - splash2
     - splash3
    ports:
      # - 8051:8051
      - "8052:8052"  
    networks:
      nginx-splash:
        aliases:
          - ns_nginx

networks:
  nginx-splash:
    driver: bridge
    # enable_ipv6: true
    ipam:
      driver: default
      config:
      - subnet: 172.16.238.0/24
        gateway: 172.16.238.1
      # - subnet: 2001:3984:3989::/64
      #   gateway: 2001:3984:3989::1